import types
from ._gi import PyGIDeprecationWarning, PyGIWarning
from _typeshed import Incomplete

__path__: Incomplete
PyGIDeprecationWarning = PyGIDeprecationWarning
PyGIWarning = PyGIWarning
version_info: Incomplete

class _DummyStaticModule(types.ModuleType):
    __path__: Incomplete
    def __getattr__(self, name) -> None: ...

def check_version(version) -> None: ...
def require_version(namespace, version) -> None: ...
def require_versions(requires) -> None: ...
def get_required_version(namespace): ...
def require_foreign(namespace, symbol: Incomplete | None = ...) -> None: ...
