from _typeshed import Incomplete

class GError(RuntimeError):
    message: Incomplete
    domain: Incomplete
    code: Incomplete
    def __init__(self, message: str = ..., domain: str = ..., code: int = ...) -> None: ...
    def copy(self): ...
    def matches(self, domain, code) -> None: ...
    @staticmethod
    def new_literal(domain, message, code) -> None: ...
