from _typeshed import Incomplete
from collections.abc import Generator

def ensure_socket_not_inheritable(sock) -> None: ...
def wakeup_on_signal() -> Generator[None, None, Incomplete]: ...

PyOS_getsig: Incomplete
startup_sigint_ptr: Incomplete

def sigint_handler_is_default(): ...
def sigint_handler_set_and_restore_default(handler) -> Generator[None, None, None]: ...
def is_main_thread(): ...
def register_sigint_fallback(callback) -> Generator[None, None, None]: ...
