import types
from _typeshed import Incomplete
from gi import PyGIDeprecationWarning as PyGIDeprecationWarning
from gi._constants import TYPE_INVALID as TYPE_INVALID, TYPE_NONE as TYPE_NONE
from gi._gi import CallableInfo as CallableInfo, pygobject_new_full as pygobject_new_full

__path__: Incomplete

class OverridesProxyModule(types.ModuleType):
    def __init__(self, introspection_module) -> None: ...
    def __getattr__(self, name): ...
    def __dir__(self): ...

class _DeprecatedAttribute:
    def __init__(self, namespace, attr, value, replacement) -> None: ...
    def __get__(self, instance, owner): ...
    def __set__(self, instance, value) -> None: ...
    def __delete__(self, instance) -> None: ...

def load_overrides(introspection_module): ...
def override(type_): ...
overridefunc = override

def deprecated(fn, replacement): ...
def deprecated_attr(namespace, attr, replacement) -> None: ...
def deprecated_init(super_init_func, arg_names, ignore=..., deprecated_aliases=..., deprecated_defaults=..., category=..., stacklevel: int = ...): ...
def strip_boolean_result(method, exc_type: Incomplete | None = ..., exc_str: Incomplete | None = ..., fail_ret: Incomplete | None = ...): ...
def wrap_list_store_sort_func(func): ...
