from _typeshed import Incomplete

OVERRIDES_CONSTANT: int

class OverridesStruct(GIMarshallingTests.OverridesStruct):
    def __new__(cls, long_): ...
    long_: Incomplete
    def __init__(self, long_) -> None: ...
    def method(self): ...

class OverridesObject(GIMarshallingTests.OverridesObject):
    def __new__(cls, long_): ...
    def __init__(self, long_) -> None: ...
    @classmethod
    def new(cls, long_): ...
    def method(self): ...
